/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MayoristasRouteImport } from './routes/mayoristas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TiendaIndexRouteImport } from './routes/tienda/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TiendaSlugRouteImport } from './routes/tienda/$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminWholesaleRouteImport } from './routes/admin/wholesale'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminEmeraldsRouteImport } from './routes/admin/emeralds'
import { Route as AdminEmeraldsNewRouteImport } from './routes/admin/emeralds.new'

const MayoristasRoute = MayoristasRouteImport.update({
  id: '/mayoristas',
  path: '/mayoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaIndexRoute = TiendaIndexRouteImport.update({
  id: '/tienda/',
  path: '/tienda/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TiendaSlugRoute = TiendaSlugRouteImport.update({
  id: '/tienda/$slug',
  path: '/tienda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWholesaleRoute = AdminWholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmeraldsRoute = AdminEmeraldsRouteImport.update({
  id: '/emeralds',
  path: '/emeralds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmeraldsNewRoute = AdminEmeraldsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEmeraldsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mayoristas': typeof MayoristasRoute
  '/admin/emeralds': typeof AdminEmeraldsRouteWithChildren
  '/admin/import': typeof AdminImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/tienda/': typeof TiendaIndexRoute
  '/admin/emeralds/new': typeof AdminEmeraldsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mayoristas': typeof MayoristasRoute
  '/admin/emeralds': typeof AdminEmeraldsRouteWithChildren
  '/admin/import': typeof AdminImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin': typeof AdminIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/tienda': typeof TiendaIndexRoute
  '/admin/emeralds/new': typeof AdminEmeraldsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mayoristas': typeof MayoristasRoute
  '/admin/emeralds': typeof AdminEmeraldsRouteWithChildren
  '/admin/import': typeof AdminImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/tienda/': typeof TiendaIndexRoute
  '/admin/emeralds/new': typeof AdminEmeraldsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/home'
    | '/login'
    | '/mayoristas'
    | '/admin/emeralds'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/wholesale'
    | '/auth/callback'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/guides/$slug'
    | '/tienda/$slug'
    | '/admin/'
    | '/guides/'
    | '/tienda/'
    | '/admin/emeralds/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/home'
    | '/login'
    | '/mayoristas'
    | '/admin/emeralds'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/wholesale'
    | '/auth/callback'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/guides/$slug'
    | '/tienda/$slug'
    | '/admin'
    | '/guides'
    | '/tienda'
    | '/admin/emeralds/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/home'
    | '/login'
    | '/mayoristas'
    | '/admin/emeralds'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/wholesale'
    | '/auth/callback'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/guides/$slug'
    | '/tienda/$slug'
    | '/admin/'
    | '/guides/'
    | '/tienda/'
    | '/admin/emeralds/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MayoristasRoute: typeof MayoristasRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  TiendaSlugRoute: typeof TiendaSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  TiendaIndexRoute: typeof TiendaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mayoristas': {
      id: '/mayoristas'
      path: '/mayoristas'
      fullPath: '/mayoristas'
      preLoaderRoute: typeof MayoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/': {
      id: '/tienda/'
      path: '/tienda'
      fullPath: '/tienda/'
      preLoaderRoute: typeof TiendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tienda/$slug': {
      id: '/tienda/$slug'
      path: '/tienda/$slug'
      fullPath: '/tienda/$slug'
      preLoaderRoute: typeof TiendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wholesale': {
      id: '/admin/wholesale'
      path: '/wholesale'
      fullPath: '/admin/wholesale'
      preLoaderRoute: typeof AdminWholesaleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emeralds': {
      id: '/admin/emeralds'
      path: '/emeralds'
      fullPath: '/admin/emeralds'
      preLoaderRoute: typeof AdminEmeraldsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emeralds/new': {
      id: '/admin/emeralds/new'
      path: '/new'
      fullPath: '/admin/emeralds/new'
      preLoaderRoute: typeof AdminEmeraldsNewRouteImport
      parentRoute: typeof AdminEmeraldsRoute
    }
  }
}

interface AdminEmeraldsRouteChildren {
  AdminEmeraldsNewRoute: typeof AdminEmeraldsNewRoute
}

const AdminEmeraldsRouteChildren: AdminEmeraldsRouteChildren = {
  AdminEmeraldsNewRoute: AdminEmeraldsNewRoute,
}

const AdminEmeraldsRouteWithChildren = AdminEmeraldsRoute._addFileChildren(
  AdminEmeraldsRouteChildren,
)

interface AdminRouteChildren {
  AdminEmeraldsRoute: typeof AdminEmeraldsRouteWithChildren
  AdminImportRoute: typeof AdminImportRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminWholesaleRoute: typeof AdminWholesaleRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEmeraldsRoute: AdminEmeraldsRouteWithChildren,
  AdminImportRoute: AdminImportRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminWholesaleRoute: AdminWholesaleRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MayoristasRoute: MayoristasRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  TiendaSlugRoute: TiendaSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  TiendaIndexRoute: TiendaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
