/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmeraldsRouteImport } from './routes/emeralds'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as EmeraldsIndexRouteImport } from './routes/emeralds/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as EmeraldsPaymentSuccessRouteImport } from './routes/emeralds/payment-success'
import { Route as EmeraldsPaymentCancelRouteImport } from './routes/emeralds/payment-cancel'
import { Route as EmeraldsMyOrderRouteImport } from './routes/emeralds/my-order'
import { Route as EmeraldsCompareRouteImport } from './routes/emeralds/compare'
import { Route as EmeraldsCheckoutRouteImport } from './routes/emeralds/checkout'
import { Route as EmeraldsCartRouteImport } from './routes/emeralds/cart'
import { Route as ApiSitemapRouteImport } from './routes/api.sitemap'
import { Route as ApiOrderRouteImport } from './routes/api.order'
import { Route as ApiNewsletterRouteImport } from './routes/api.newsletter'
import { Route as ApiLlmsFullRouteImport } from './routes/api.llms-full'
import { Route as ApiLlmsRouteImport } from './routes/api.llms'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as EmeraldsShopIndexRouteImport } from './routes/emeralds/shop/index'
import { Route as EmeraldsShopSlugRouteImport } from './routes/emeralds/shop/$slug'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api.whatsapp.webhook'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api.stripe.checkout'
import { Route as ApiPromoValidateRouteImport } from './routes/api.promo.validate'
import { Route as ApiOrdersOrderIdRouteImport } from './routes/api.orders.$orderId'
import { Route as ApiOrderLookupRouteImport } from './routes/api.order.lookup'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmeraldsRoute = EmeraldsRouteImport.update({
  id: '/emeralds',
  path: '/emeralds',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmeraldsIndexRoute = EmeraldsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmeraldsRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmeraldsPaymentSuccessRoute = EmeraldsPaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsPaymentCancelRoute = EmeraldsPaymentCancelRouteImport.update({
  id: '/payment-cancel',
  path: '/payment-cancel',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsMyOrderRoute = EmeraldsMyOrderRouteImport.update({
  id: '/my-order',
  path: '/my-order',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsCompareRoute = EmeraldsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsCheckoutRoute = EmeraldsCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsCartRoute = EmeraldsCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => EmeraldsRoute,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrderRoute = ApiOrderRouteImport.update({
  id: '/api/order',
  path: '/api/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({
  id: '/api/newsletter',
  path: '/api/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmsFullRoute = ApiLlmsFullRouteImport.update({
  id: '/api/llms-full',
  path: '/api/llms-full',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmsRoute = ApiLlmsRouteImport.update({
  id: '/api/llms',
  path: '/api/llms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmeraldsShopIndexRoute = EmeraldsShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsShopSlugRoute = EmeraldsShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => EmeraldsRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromoValidateRoute = ApiPromoValidateRouteImport.update({
  id: '/api/promo/validate',
  path: '/api/promo/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersOrderIdRoute = ApiOrdersOrderIdRouteImport.update({
  id: '/api/orders/$orderId',
  path: '/api/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrderLookupRoute = ApiOrderLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => ApiOrderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emeralds': typeof EmeraldsRouteWithChildren
  '/faq': typeof FaqRoute
  '/api/contact': typeof ApiContactRoute
  '/api/llms': typeof ApiLlmsRoute
  '/api/llms-full': typeof ApiLlmsFullRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/order': typeof ApiOrderRouteWithChildren
  '/api/sitemap': typeof ApiSitemapRoute
  '/emeralds/cart': typeof EmeraldsCartRoute
  '/emeralds/checkout': typeof EmeraldsCheckoutRoute
  '/emeralds/compare': typeof EmeraldsCompareRoute
  '/emeralds/my-order': typeof EmeraldsMyOrderRoute
  '/emeralds/payment-cancel': typeof EmeraldsPaymentCancelRoute
  '/emeralds/payment-success': typeof EmeraldsPaymentSuccessRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/emeralds/': typeof EmeraldsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/order/lookup': typeof ApiOrderLookupRoute
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/promo/validate': typeof ApiPromoValidateRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/emeralds/shop/$slug': typeof EmeraldsShopSlugRoute
  '/emeralds/shop/': typeof EmeraldsShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/api/contact': typeof ApiContactRoute
  '/api/llms': typeof ApiLlmsRoute
  '/api/llms-full': typeof ApiLlmsFullRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/order': typeof ApiOrderRouteWithChildren
  '/api/sitemap': typeof ApiSitemapRoute
  '/emeralds/cart': typeof EmeraldsCartRoute
  '/emeralds/checkout': typeof EmeraldsCheckoutRoute
  '/emeralds/compare': typeof EmeraldsCompareRoute
  '/emeralds/my-order': typeof EmeraldsMyOrderRoute
  '/emeralds/payment-cancel': typeof EmeraldsPaymentCancelRoute
  '/emeralds/payment-success': typeof EmeraldsPaymentSuccessRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/emeralds': typeof EmeraldsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/api/order/lookup': typeof ApiOrderLookupRoute
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/promo/validate': typeof ApiPromoValidateRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/emeralds/shop/$slug': typeof EmeraldsShopSlugRoute
  '/emeralds/shop': typeof EmeraldsShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emeralds': typeof EmeraldsRouteWithChildren
  '/faq': typeof FaqRoute
  '/api/contact': typeof ApiContactRoute
  '/api/llms': typeof ApiLlmsRoute
  '/api/llms-full': typeof ApiLlmsFullRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/order': typeof ApiOrderRouteWithChildren
  '/api/sitemap': typeof ApiSitemapRoute
  '/emeralds/cart': typeof EmeraldsCartRoute
  '/emeralds/checkout': typeof EmeraldsCheckoutRoute
  '/emeralds/compare': typeof EmeraldsCompareRoute
  '/emeralds/my-order': typeof EmeraldsMyOrderRoute
  '/emeralds/payment-cancel': typeof EmeraldsPaymentCancelRoute
  '/emeralds/payment-success': typeof EmeraldsPaymentSuccessRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/emeralds/': typeof EmeraldsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/order/lookup': typeof ApiOrderLookupRoute
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/promo/validate': typeof ApiPromoValidateRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/emeralds/shop/$slug': typeof EmeraldsShopSlugRoute
  '/emeralds/shop/': typeof EmeraldsShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/emeralds'
    | '/faq'
    | '/api/contact'
    | '/api/llms'
    | '/api/llms-full'
    | '/api/newsletter'
    | '/api/order'
    | '/api/sitemap'
    | '/emeralds/cart'
    | '/emeralds/checkout'
    | '/emeralds/compare'
    | '/emeralds/my-order'
    | '/emeralds/payment-cancel'
    | '/emeralds/payment-success'
    | '/guides/$slug'
    | '/emeralds/'
    | '/guides/'
    | '/api/order/lookup'
    | '/api/orders/$orderId'
    | '/api/promo/validate'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/whatsapp/webhook'
    | '/emeralds/shop/$slug'
    | '/emeralds/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/api/contact'
    | '/api/llms'
    | '/api/llms-full'
    | '/api/newsletter'
    | '/api/order'
    | '/api/sitemap'
    | '/emeralds/cart'
    | '/emeralds/checkout'
    | '/emeralds/compare'
    | '/emeralds/my-order'
    | '/emeralds/payment-cancel'
    | '/emeralds/payment-success'
    | '/guides/$slug'
    | '/emeralds'
    | '/guides'
    | '/api/order/lookup'
    | '/api/orders/$orderId'
    | '/api/promo/validate'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/whatsapp/webhook'
    | '/emeralds/shop/$slug'
    | '/emeralds/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/emeralds'
    | '/faq'
    | '/api/contact'
    | '/api/llms'
    | '/api/llms-full'
    | '/api/newsletter'
    | '/api/order'
    | '/api/sitemap'
    | '/emeralds/cart'
    | '/emeralds/checkout'
    | '/emeralds/compare'
    | '/emeralds/my-order'
    | '/emeralds/payment-cancel'
    | '/emeralds/payment-success'
    | '/guides/$slug'
    | '/emeralds/'
    | '/guides/'
    | '/api/order/lookup'
    | '/api/orders/$orderId'
    | '/api/promo/validate'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/whatsapp/webhook'
    | '/emeralds/shop/$slug'
    | '/emeralds/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EmeraldsRoute: typeof EmeraldsRouteWithChildren
  FaqRoute: typeof FaqRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiLlmsRoute: typeof ApiLlmsRoute
  ApiLlmsFullRoute: typeof ApiLlmsFullRoute
  ApiNewsletterRoute: typeof ApiNewsletterRoute
  ApiOrderRoute: typeof ApiOrderRouteWithChildren
  ApiSitemapRoute: typeof ApiSitemapRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ApiOrdersOrderIdRoute: typeof ApiOrdersOrderIdRoute
  ApiPromoValidateRoute: typeof ApiPromoValidateRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emeralds': {
      id: '/emeralds'
      path: '/emeralds'
      fullPath: '/emeralds'
      preLoaderRoute: typeof EmeraldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emeralds/': {
      id: '/emeralds/'
      path: '/'
      fullPath: '/emeralds/'
      preLoaderRoute: typeof EmeraldsIndexRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emeralds/payment-success': {
      id: '/emeralds/payment-success'
      path: '/payment-success'
      fullPath: '/emeralds/payment-success'
      preLoaderRoute: typeof EmeraldsPaymentSuccessRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/payment-cancel': {
      id: '/emeralds/payment-cancel'
      path: '/payment-cancel'
      fullPath: '/emeralds/payment-cancel'
      preLoaderRoute: typeof EmeraldsPaymentCancelRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/my-order': {
      id: '/emeralds/my-order'
      path: '/my-order'
      fullPath: '/emeralds/my-order'
      preLoaderRoute: typeof EmeraldsMyOrderRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/compare': {
      id: '/emeralds/compare'
      path: '/compare'
      fullPath: '/emeralds/compare'
      preLoaderRoute: typeof EmeraldsCompareRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/checkout': {
      id: '/emeralds/checkout'
      path: '/checkout'
      fullPath: '/emeralds/checkout'
      preLoaderRoute: typeof EmeraldsCheckoutRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/cart': {
      id: '/emeralds/cart'
      path: '/cart'
      fullPath: '/emeralds/cart'
      preLoaderRoute: typeof EmeraldsCartRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/order': {
      id: '/api/order'
      path: '/api/order'
      fullPath: '/api/order'
      preLoaderRoute: typeof ApiOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter': {
      id: '/api/newsletter'
      path: '/api/newsletter'
      fullPath: '/api/newsletter'
      preLoaderRoute: typeof ApiNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llms-full': {
      id: '/api/llms-full'
      path: '/api/llms-full'
      fullPath: '/api/llms-full'
      preLoaderRoute: typeof ApiLlmsFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llms': {
      id: '/api/llms'
      path: '/api/llms'
      fullPath: '/api/llms'
      preLoaderRoute: typeof ApiLlmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emeralds/shop/': {
      id: '/emeralds/shop/'
      path: '/shop'
      fullPath: '/emeralds/shop/'
      preLoaderRoute: typeof EmeraldsShopIndexRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/shop/$slug': {
      id: '/emeralds/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/emeralds/shop/$slug'
      preLoaderRoute: typeof EmeraldsShopSlugRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promo/validate': {
      id: '/api/promo/validate'
      path: '/api/promo/validate'
      fullPath: '/api/promo/validate'
      preLoaderRoute: typeof ApiPromoValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$orderId': {
      id: '/api/orders/$orderId'
      path: '/api/orders/$orderId'
      fullPath: '/api/orders/$orderId'
      preLoaderRoute: typeof ApiOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/order/lookup': {
      id: '/api/order/lookup'
      path: '/lookup'
      fullPath: '/api/order/lookup'
      preLoaderRoute: typeof ApiOrderLookupRouteImport
      parentRoute: typeof ApiOrderRoute
    }
  }
}

interface EmeraldsRouteChildren {
  EmeraldsCartRoute: typeof EmeraldsCartRoute
  EmeraldsCheckoutRoute: typeof EmeraldsCheckoutRoute
  EmeraldsCompareRoute: typeof EmeraldsCompareRoute
  EmeraldsMyOrderRoute: typeof EmeraldsMyOrderRoute
  EmeraldsPaymentCancelRoute: typeof EmeraldsPaymentCancelRoute
  EmeraldsPaymentSuccessRoute: typeof EmeraldsPaymentSuccessRoute
  EmeraldsIndexRoute: typeof EmeraldsIndexRoute
  EmeraldsShopSlugRoute: typeof EmeraldsShopSlugRoute
  EmeraldsShopIndexRoute: typeof EmeraldsShopIndexRoute
}

const EmeraldsRouteChildren: EmeraldsRouteChildren = {
  EmeraldsCartRoute: EmeraldsCartRoute,
  EmeraldsCheckoutRoute: EmeraldsCheckoutRoute,
  EmeraldsCompareRoute: EmeraldsCompareRoute,
  EmeraldsMyOrderRoute: EmeraldsMyOrderRoute,
  EmeraldsPaymentCancelRoute: EmeraldsPaymentCancelRoute,
  EmeraldsPaymentSuccessRoute: EmeraldsPaymentSuccessRoute,
  EmeraldsIndexRoute: EmeraldsIndexRoute,
  EmeraldsShopSlugRoute: EmeraldsShopSlugRoute,
  EmeraldsShopIndexRoute: EmeraldsShopIndexRoute,
}

const EmeraldsRouteWithChildren = EmeraldsRoute._addFileChildren(
  EmeraldsRouteChildren,
)

interface ApiOrderRouteChildren {
  ApiOrderLookupRoute: typeof ApiOrderLookupRoute
}

const ApiOrderRouteChildren: ApiOrderRouteChildren = {
  ApiOrderLookupRoute: ApiOrderLookupRoute,
}

const ApiOrderRouteWithChildren = ApiOrderRoute._addFileChildren(
  ApiOrderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EmeraldsRoute: EmeraldsRouteWithChildren,
  FaqRoute: FaqRoute,
  ApiContactRoute: ApiContactRoute,
  ApiLlmsRoute: ApiLlmsRoute,
  ApiLlmsFullRoute: ApiLlmsFullRoute,
  ApiNewsletterRoute: ApiNewsletterRoute,
  ApiOrderRoute: ApiOrderRouteWithChildren,
  ApiSitemapRoute: ApiSitemapRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ApiOrdersOrderIdRoute: ApiOrdersOrderIdRoute,
  ApiPromoValidateRoute: ApiPromoValidateRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
