/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmeraldsRouteImport } from './routes/emeralds'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as EmeraldsIndexRouteImport } from './routes/emeralds/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as EmeraldsCompareRouteImport } from './routes/emeralds/compare'
import { Route as EmeraldsCheckoutRouteImport } from './routes/emeralds/checkout'
import { Route as EmeraldsCartRouteImport } from './routes/emeralds/cart'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminWholesaleRouteImport } from './routes/admin/wholesale'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminEmeraldsRouteImport } from './routes/admin/emeralds'
import { Route as EmeraldsShopIndexRouteImport } from './routes/emeralds/shop/index'
import { Route as EmeraldsShopSlugRouteImport } from './routes/emeralds/shop/$slug'
import { Route as EmeraldsCheckoutSuccessRouteImport } from './routes/emeralds/checkout.success'
import { Route as EmeraldsCheckoutCancelRouteImport } from './routes/emeralds/checkout.cancel'
import { Route as AdminEmeraldsNewRouteImport } from './routes/admin/emeralds.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmeraldsRoute = EmeraldsRouteImport.update({
  id: '/emeralds',
  path: '/emeralds',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmeraldsIndexRoute = EmeraldsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmeraldsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmeraldsCompareRoute = EmeraldsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsCheckoutRoute = EmeraldsCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsCartRoute = EmeraldsCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => EmeraldsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWholesaleRoute = AdminWholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmeraldsRoute = AdminEmeraldsRouteImport.update({
  id: '/emeralds',
  path: '/emeralds',
  getParentRoute: () => AdminRoute,
} as any)
const EmeraldsShopIndexRoute = EmeraldsShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsShopSlugRoute = EmeraldsShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsCheckoutSuccessRoute = EmeraldsCheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => EmeraldsCheckoutRoute,
} as any)
const EmeraldsCheckoutCancelRoute = EmeraldsCheckoutCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => EmeraldsCheckoutRoute,
} as any)
const AdminEmeraldsNewRoute = AdminEmeraldsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEmeraldsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/emeralds': typeof EmeraldsRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/admin/emeralds': typeof AdminEmeraldsRouteWithChildren
  '/admin/import': typeof AdminImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/emeralds/cart': typeof EmeraldsCartRoute
  '/emeralds/checkout': typeof EmeraldsCheckoutRouteWithChildren
  '/emeralds/compare': typeof EmeraldsCompareRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/emeralds/': typeof EmeraldsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/admin/emeralds/new': typeof AdminEmeraldsNewRoute
  '/emeralds/checkout/cancel': typeof EmeraldsCheckoutCancelRoute
  '/emeralds/checkout/success': typeof EmeraldsCheckoutSuccessRoute
  '/emeralds/shop/$slug': typeof EmeraldsShopSlugRoute
  '/emeralds/shop/': typeof EmeraldsShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/admin/emeralds': typeof AdminEmeraldsRouteWithChildren
  '/admin/import': typeof AdminImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/emeralds/cart': typeof EmeraldsCartRoute
  '/emeralds/checkout': typeof EmeraldsCheckoutRouteWithChildren
  '/emeralds/compare': typeof EmeraldsCompareRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/emeralds': typeof EmeraldsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/admin/emeralds/new': typeof AdminEmeraldsNewRoute
  '/emeralds/checkout/cancel': typeof EmeraldsCheckoutCancelRoute
  '/emeralds/checkout/success': typeof EmeraldsCheckoutSuccessRoute
  '/emeralds/shop/$slug': typeof EmeraldsShopSlugRoute
  '/emeralds/shop': typeof EmeraldsShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/emeralds': typeof EmeraldsRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/admin/emeralds': typeof AdminEmeraldsRouteWithChildren
  '/admin/import': typeof AdminImportRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/wholesale': typeof AdminWholesaleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/emeralds/cart': typeof EmeraldsCartRoute
  '/emeralds/checkout': typeof EmeraldsCheckoutRouteWithChildren
  '/emeralds/compare': typeof EmeraldsCompareRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/emeralds/': typeof EmeraldsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/admin/emeralds/new': typeof AdminEmeraldsNewRoute
  '/emeralds/checkout/cancel': typeof EmeraldsCheckoutCancelRoute
  '/emeralds/checkout/success': typeof EmeraldsCheckoutSuccessRoute
  '/emeralds/shop/$slug': typeof EmeraldsShopSlugRoute
  '/emeralds/shop/': typeof EmeraldsShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/emeralds'
    | '/faq'
    | '/login'
    | '/admin/emeralds'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/wholesale'
    | '/auth/callback'
    | '/emeralds/cart'
    | '/emeralds/checkout'
    | '/emeralds/compare'
    | '/guides/$slug'
    | '/admin/'
    | '/emeralds/'
    | '/guides/'
    | '/admin/emeralds/new'
    | '/emeralds/checkout/cancel'
    | '/emeralds/checkout/success'
    | '/emeralds/shop/$slug'
    | '/emeralds/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/admin/emeralds'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/wholesale'
    | '/auth/callback'
    | '/emeralds/cart'
    | '/emeralds/checkout'
    | '/emeralds/compare'
    | '/guides/$slug'
    | '/admin'
    | '/emeralds'
    | '/guides'
    | '/admin/emeralds/new'
    | '/emeralds/checkout/cancel'
    | '/emeralds/checkout/success'
    | '/emeralds/shop/$slug'
    | '/emeralds/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/emeralds'
    | '/faq'
    | '/login'
    | '/admin/emeralds'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/wholesale'
    | '/auth/callback'
    | '/emeralds/cart'
    | '/emeralds/checkout'
    | '/emeralds/compare'
    | '/guides/$slug'
    | '/admin/'
    | '/emeralds/'
    | '/guides/'
    | '/admin/emeralds/new'
    | '/emeralds/checkout/cancel'
    | '/emeralds/checkout/success'
    | '/emeralds/shop/$slug'
    | '/emeralds/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  EmeraldsRoute: typeof EmeraldsRouteWithChildren
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emeralds': {
      id: '/emeralds'
      path: '/emeralds'
      fullPath: '/emeralds'
      preLoaderRoute: typeof EmeraldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emeralds/': {
      id: '/emeralds/'
      path: '/'
      fullPath: '/emeralds/'
      preLoaderRoute: typeof EmeraldsIndexRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emeralds/compare': {
      id: '/emeralds/compare'
      path: '/compare'
      fullPath: '/emeralds/compare'
      preLoaderRoute: typeof EmeraldsCompareRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/checkout': {
      id: '/emeralds/checkout'
      path: '/checkout'
      fullPath: '/emeralds/checkout'
      preLoaderRoute: typeof EmeraldsCheckoutRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/cart': {
      id: '/emeralds/cart'
      path: '/cart'
      fullPath: '/emeralds/cart'
      preLoaderRoute: typeof EmeraldsCartRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wholesale': {
      id: '/admin/wholesale'
      path: '/wholesale'
      fullPath: '/admin/wholesale'
      preLoaderRoute: typeof AdminWholesaleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emeralds': {
      id: '/admin/emeralds'
      path: '/emeralds'
      fullPath: '/admin/emeralds'
      preLoaderRoute: typeof AdminEmeraldsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/emeralds/shop/': {
      id: '/emeralds/shop/'
      path: '/shop'
      fullPath: '/emeralds/shop/'
      preLoaderRoute: typeof EmeraldsShopIndexRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/shop/$slug': {
      id: '/emeralds/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/emeralds/shop/$slug'
      preLoaderRoute: typeof EmeraldsShopSlugRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/checkout/success': {
      id: '/emeralds/checkout/success'
      path: '/success'
      fullPath: '/emeralds/checkout/success'
      preLoaderRoute: typeof EmeraldsCheckoutSuccessRouteImport
      parentRoute: typeof EmeraldsCheckoutRoute
    }
    '/emeralds/checkout/cancel': {
      id: '/emeralds/checkout/cancel'
      path: '/cancel'
      fullPath: '/emeralds/checkout/cancel'
      preLoaderRoute: typeof EmeraldsCheckoutCancelRouteImport
      parentRoute: typeof EmeraldsCheckoutRoute
    }
    '/admin/emeralds/new': {
      id: '/admin/emeralds/new'
      path: '/new'
      fullPath: '/admin/emeralds/new'
      preLoaderRoute: typeof AdminEmeraldsNewRouteImport
      parentRoute: typeof AdminEmeraldsRoute
    }
  }
}

interface AdminEmeraldsRouteChildren {
  AdminEmeraldsNewRoute: typeof AdminEmeraldsNewRoute
}

const AdminEmeraldsRouteChildren: AdminEmeraldsRouteChildren = {
  AdminEmeraldsNewRoute: AdminEmeraldsNewRoute,
}

const AdminEmeraldsRouteWithChildren = AdminEmeraldsRoute._addFileChildren(
  AdminEmeraldsRouteChildren,
)

interface AdminRouteChildren {
  AdminEmeraldsRoute: typeof AdminEmeraldsRouteWithChildren
  AdminImportRoute: typeof AdminImportRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminWholesaleRoute: typeof AdminWholesaleRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEmeraldsRoute: AdminEmeraldsRouteWithChildren,
  AdminImportRoute: AdminImportRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminWholesaleRoute: AdminWholesaleRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmeraldsCheckoutRouteChildren {
  EmeraldsCheckoutCancelRoute: typeof EmeraldsCheckoutCancelRoute
  EmeraldsCheckoutSuccessRoute: typeof EmeraldsCheckoutSuccessRoute
}

const EmeraldsCheckoutRouteChildren: EmeraldsCheckoutRouteChildren = {
  EmeraldsCheckoutCancelRoute: EmeraldsCheckoutCancelRoute,
  EmeraldsCheckoutSuccessRoute: EmeraldsCheckoutSuccessRoute,
}

const EmeraldsCheckoutRouteWithChildren =
  EmeraldsCheckoutRoute._addFileChildren(EmeraldsCheckoutRouteChildren)

interface EmeraldsRouteChildren {
  EmeraldsCartRoute: typeof EmeraldsCartRoute
  EmeraldsCheckoutRoute: typeof EmeraldsCheckoutRouteWithChildren
  EmeraldsCompareRoute: typeof EmeraldsCompareRoute
  EmeraldsIndexRoute: typeof EmeraldsIndexRoute
  EmeraldsShopSlugRoute: typeof EmeraldsShopSlugRoute
  EmeraldsShopIndexRoute: typeof EmeraldsShopIndexRoute
}

const EmeraldsRouteChildren: EmeraldsRouteChildren = {
  EmeraldsCartRoute: EmeraldsCartRoute,
  EmeraldsCheckoutRoute: EmeraldsCheckoutRouteWithChildren,
  EmeraldsCompareRoute: EmeraldsCompareRoute,
  EmeraldsIndexRoute: EmeraldsIndexRoute,
  EmeraldsShopSlugRoute: EmeraldsShopSlugRoute,
  EmeraldsShopIndexRoute: EmeraldsShopIndexRoute,
}

const EmeraldsRouteWithChildren = EmeraldsRoute._addFileChildren(
  EmeraldsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  EmeraldsRoute: EmeraldsRouteWithChildren,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
