/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthWholesaleRouteImport } from './routes/_auth/wholesale'
import { Route as AuthPromotionsRouteImport } from './routes/_auth/promotions'
import { Route as AuthOrdersRouteImport } from './routes/_auth/orders'
import { Route as AuthImportRouteImport } from './routes/_auth/import'
import { Route as AuthEmeraldsRouteImport } from './routes/_auth/emeralds'
import { Route as AuthEmeraldsNewRouteImport } from './routes/_auth/emeralds.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWholesaleRoute = AuthWholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPromotionsRoute = AuthPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersRoute = AuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImportRoute = AuthImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmeraldsRoute = AuthEmeraldsRouteImport.update({
  id: '/emeralds',
  path: '/emeralds',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmeraldsNewRoute = AuthEmeraldsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthEmeraldsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/emeralds': typeof AuthEmeraldsRouteWithChildren
  '/import': typeof AuthImportRoute
  '/orders': typeof AuthOrdersRoute
  '/promotions': typeof AuthPromotionsRoute
  '/wholesale': typeof AuthWholesaleRoute
  '/emeralds/new': typeof AuthEmeraldsNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/emeralds': typeof AuthEmeraldsRouteWithChildren
  '/import': typeof AuthImportRoute
  '/orders': typeof AuthOrdersRoute
  '/promotions': typeof AuthPromotionsRoute
  '/wholesale': typeof AuthWholesaleRoute
  '/': typeof AuthIndexRoute
  '/emeralds/new': typeof AuthEmeraldsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/emeralds': typeof AuthEmeraldsRouteWithChildren
  '/_auth/import': typeof AuthImportRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/_auth/promotions': typeof AuthPromotionsRoute
  '/_auth/wholesale': typeof AuthWholesaleRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/emeralds/new': typeof AuthEmeraldsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/emeralds'
    | '/import'
    | '/orders'
    | '/promotions'
    | '/wholesale'
    | '/emeralds/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/emeralds'
    | '/import'
    | '/orders'
    | '/promotions'
    | '/wholesale'
    | '/'
    | '/emeralds/new'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/emeralds'
    | '/_auth/import'
    | '/_auth/orders'
    | '/_auth/promotions'
    | '/_auth/wholesale'
    | '/_auth/'
    | '/_auth/emeralds/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/wholesale': {
      id: '/_auth/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof AuthWholesaleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/promotions': {
      id: '/_auth/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthPromotionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/import': {
      id: '/_auth/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthImportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/emeralds': {
      id: '/_auth/emeralds'
      path: '/emeralds'
      fullPath: '/emeralds'
      preLoaderRoute: typeof AuthEmeraldsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/emeralds/new': {
      id: '/_auth/emeralds/new'
      path: '/new'
      fullPath: '/emeralds/new'
      preLoaderRoute: typeof AuthEmeraldsNewRouteImport
      parentRoute: typeof AuthEmeraldsRoute
    }
  }
}

interface AuthEmeraldsRouteChildren {
  AuthEmeraldsNewRoute: typeof AuthEmeraldsNewRoute
}

const AuthEmeraldsRouteChildren: AuthEmeraldsRouteChildren = {
  AuthEmeraldsNewRoute: AuthEmeraldsNewRoute,
}

const AuthEmeraldsRouteWithChildren = AuthEmeraldsRoute._addFileChildren(
  AuthEmeraldsRouteChildren,
)

interface AuthRouteChildren {
  AuthEmeraldsRoute: typeof AuthEmeraldsRouteWithChildren
  AuthImportRoute: typeof AuthImportRoute
  AuthOrdersRoute: typeof AuthOrdersRoute
  AuthPromotionsRoute: typeof AuthPromotionsRoute
  AuthWholesaleRoute: typeof AuthWholesaleRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEmeraldsRoute: AuthEmeraldsRouteWithChildren,
  AuthImportRoute: AuthImportRoute,
  AuthOrdersRoute: AuthOrdersRoute,
  AuthPromotionsRoute: AuthPromotionsRoute,
  AuthWholesaleRoute: AuthWholesaleRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
