/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreJeweleryIndexRouteImport } from './routes/_store.jewelery/index'
import { Route as StoreEmeraldsIndexRouteImport } from './routes/_store.emeralds/index'
import { Route as StoreEmeraldsTiendaRouteImport } from './routes/_store.emeralds/tienda'
import { Route as StoreEmeraldsMayoristasRouteImport } from './routes/_store.emeralds/mayoristas'

const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreJeweleryIndexRoute = StoreJeweleryIndexRouteImport.update({
  id: '/jewelery/',
  path: '/jewelery/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreEmeraldsIndexRoute = StoreEmeraldsIndexRouteImport.update({
  id: '/emeralds/',
  path: '/emeralds/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreEmeraldsTiendaRoute = StoreEmeraldsTiendaRouteImport.update({
  id: '/emeralds/tienda',
  path: '/emeralds/tienda',
  getParentRoute: () => StoreRoute,
} as any)
const StoreEmeraldsMayoristasRoute = StoreEmeraldsMayoristasRouteImport.update({
  id: '/emeralds/mayoristas',
  path: '/emeralds/mayoristas',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emeralds/mayoristas': typeof StoreEmeraldsMayoristasRoute
  '/emeralds/tienda': typeof StoreEmeraldsTiendaRoute
  '/emeralds/': typeof StoreEmeraldsIndexRoute
  '/jewelery/': typeof StoreJeweleryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emeralds/mayoristas': typeof StoreEmeraldsMayoristasRoute
  '/emeralds/tienda': typeof StoreEmeraldsTiendaRoute
  '/emeralds': typeof StoreEmeraldsIndexRoute
  '/jewelery': typeof StoreJeweleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_store': typeof StoreRouteWithChildren
  '/_store/emeralds/mayoristas': typeof StoreEmeraldsMayoristasRoute
  '/_store/emeralds/tienda': typeof StoreEmeraldsTiendaRoute
  '/_store/emeralds/': typeof StoreEmeraldsIndexRoute
  '/_store/jewelery/': typeof StoreJeweleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emeralds/mayoristas'
    | '/emeralds/tienda'
    | '/emeralds/'
    | '/jewelery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emeralds/mayoristas'
    | '/emeralds/tienda'
    | '/emeralds'
    | '/jewelery'
  id:
    | '__root__'
    | '/'
    | '/_store'
    | '/_store/emeralds/mayoristas'
    | '/_store/emeralds/tienda'
    | '/_store/emeralds/'
    | '/_store/jewelery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreRoute: typeof StoreRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store/jewelery/': {
      id: '/_store/jewelery/'
      path: '/jewelery'
      fullPath: '/jewelery/'
      preLoaderRoute: typeof StoreJeweleryIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/emeralds/': {
      id: '/_store/emeralds/'
      path: '/emeralds'
      fullPath: '/emeralds/'
      preLoaderRoute: typeof StoreEmeraldsIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/emeralds/tienda': {
      id: '/_store/emeralds/tienda'
      path: '/emeralds/tienda'
      fullPath: '/emeralds/tienda'
      preLoaderRoute: typeof StoreEmeraldsTiendaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/emeralds/mayoristas': {
      id: '/_store/emeralds/mayoristas'
      path: '/emeralds/mayoristas'
      fullPath: '/emeralds/mayoristas'
      preLoaderRoute: typeof StoreEmeraldsMayoristasRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface StoreRouteChildren {
  StoreEmeraldsMayoristasRoute: typeof StoreEmeraldsMayoristasRoute
  StoreEmeraldsTiendaRoute: typeof StoreEmeraldsTiendaRoute
  StoreEmeraldsIndexRoute: typeof StoreEmeraldsIndexRoute
  StoreJeweleryIndexRoute: typeof StoreJeweleryIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreEmeraldsMayoristasRoute: StoreEmeraldsMayoristasRoute,
  StoreEmeraldsTiendaRoute: StoreEmeraldsTiendaRoute,
  StoreEmeraldsIndexRoute: StoreEmeraldsIndexRoute,
  StoreJeweleryIndexRoute: StoreJeweleryIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreRoute: StoreRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
