/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JewelryRouteImport } from './routes/jewelry'
import { Route as EmeraldsRouteImport } from './routes/emeralds'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JewelryIndexRouteImport } from './routes/jewelry/index'
import { Route as EmeraldsTiendaRouteImport } from './routes/emeralds/tienda'
import { Route as EmeraldsMayoristasRouteImport } from './routes/emeralds/mayoristas'
import { Route as EmeraldsCompareRouteImport } from './routes/emeralds/compare'
import { Route as EmeraldsCollectionRouteImport } from './routes/emeralds/collection'

const JewelryRoute = JewelryRouteImport.update({
  id: '/jewelry',
  path: '/jewelry',
  getParentRoute: () => rootRouteImport,
} as any)
const EmeraldsRoute = EmeraldsRouteImport.update({
  id: '/emeralds',
  path: '/emeralds',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelryIndexRoute = JewelryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JewelryRoute,
} as any)
const EmeraldsTiendaRoute = EmeraldsTiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsMayoristasRoute = EmeraldsMayoristasRouteImport.update({
  id: '/mayoristas',
  path: '/mayoristas',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsCompareRoute = EmeraldsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => EmeraldsRoute,
} as any)
const EmeraldsCollectionRoute = EmeraldsCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => EmeraldsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emeralds': typeof EmeraldsRouteWithChildren
  '/jewelry': typeof JewelryRouteWithChildren
  '/emeralds/collection': typeof EmeraldsCollectionRoute
  '/emeralds/compare': typeof EmeraldsCompareRoute
  '/emeralds/mayoristas': typeof EmeraldsMayoristasRoute
  '/emeralds/tienda': typeof EmeraldsTiendaRoute
  '/jewelry/': typeof JewelryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emeralds': typeof EmeraldsRouteWithChildren
  '/emeralds/collection': typeof EmeraldsCollectionRoute
  '/emeralds/compare': typeof EmeraldsCompareRoute
  '/emeralds/mayoristas': typeof EmeraldsMayoristasRoute
  '/emeralds/tienda': typeof EmeraldsTiendaRoute
  '/jewelry': typeof JewelryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emeralds': typeof EmeraldsRouteWithChildren
  '/jewelry': typeof JewelryRouteWithChildren
  '/emeralds/collection': typeof EmeraldsCollectionRoute
  '/emeralds/compare': typeof EmeraldsCompareRoute
  '/emeralds/mayoristas': typeof EmeraldsMayoristasRoute
  '/emeralds/tienda': typeof EmeraldsTiendaRoute
  '/jewelry/': typeof JewelryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/emeralds'
    | '/jewelry'
    | '/emeralds/collection'
    | '/emeralds/compare'
    | '/emeralds/mayoristas'
    | '/emeralds/tienda'
    | '/jewelry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/emeralds'
    | '/emeralds/collection'
    | '/emeralds/compare'
    | '/emeralds/mayoristas'
    | '/emeralds/tienda'
    | '/jewelry'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/emeralds'
    | '/jewelry'
    | '/emeralds/collection'
    | '/emeralds/compare'
    | '/emeralds/mayoristas'
    | '/emeralds/tienda'
    | '/jewelry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EmeraldsRoute: typeof EmeraldsRouteWithChildren
  JewelryRoute: typeof JewelryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jewelry': {
      id: '/jewelry'
      path: '/jewelry'
      fullPath: '/jewelry'
      preLoaderRoute: typeof JewelryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emeralds': {
      id: '/emeralds'
      path: '/emeralds'
      fullPath: '/emeralds'
      preLoaderRoute: typeof EmeraldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewelry/': {
      id: '/jewelry/'
      path: '/'
      fullPath: '/jewelry/'
      preLoaderRoute: typeof JewelryIndexRouteImport
      parentRoute: typeof JewelryRoute
    }
    '/emeralds/tienda': {
      id: '/emeralds/tienda'
      path: '/tienda'
      fullPath: '/emeralds/tienda'
      preLoaderRoute: typeof EmeraldsTiendaRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/mayoristas': {
      id: '/emeralds/mayoristas'
      path: '/mayoristas'
      fullPath: '/emeralds/mayoristas'
      preLoaderRoute: typeof EmeraldsMayoristasRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/compare': {
      id: '/emeralds/compare'
      path: '/compare'
      fullPath: '/emeralds/compare'
      preLoaderRoute: typeof EmeraldsCompareRouteImport
      parentRoute: typeof EmeraldsRoute
    }
    '/emeralds/collection': {
      id: '/emeralds/collection'
      path: '/collection'
      fullPath: '/emeralds/collection'
      preLoaderRoute: typeof EmeraldsCollectionRouteImport
      parentRoute: typeof EmeraldsRoute
    }
  }
}

interface EmeraldsRouteChildren {
  EmeraldsCollectionRoute: typeof EmeraldsCollectionRoute
  EmeraldsCompareRoute: typeof EmeraldsCompareRoute
  EmeraldsMayoristasRoute: typeof EmeraldsMayoristasRoute
  EmeraldsTiendaRoute: typeof EmeraldsTiendaRoute
}

const EmeraldsRouteChildren: EmeraldsRouteChildren = {
  EmeraldsCollectionRoute: EmeraldsCollectionRoute,
  EmeraldsCompareRoute: EmeraldsCompareRoute,
  EmeraldsMayoristasRoute: EmeraldsMayoristasRoute,
  EmeraldsTiendaRoute: EmeraldsTiendaRoute,
}

const EmeraldsRouteWithChildren = EmeraldsRoute._addFileChildren(
  EmeraldsRouteChildren,
)

interface JewelryRouteChildren {
  JewelryIndexRoute: typeof JewelryIndexRoute
}

const JewelryRouteChildren: JewelryRouteChildren = {
  JewelryIndexRoute: JewelryIndexRoute,
}

const JewelryRouteWithChildren =
  JewelryRoute._addFileChildren(JewelryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EmeraldsRoute: EmeraldsRouteWithChildren,
  JewelryRoute: JewelryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
